### ISSUE TITLE
Cannot rerun pytri functions after first call

### ISSUE THREAD

**Issue by j6k4m8** [iscoe/pytri#18]
Try this:

1
```
from pytri import pytri
```
2
```
p = pytri()
```
3
```
p.axes()
p.show()
```

...and run cell 3 twice. It seems to break irreparably, until tab reload.

**Comment by j6k4m8** [comment]
Returns a `Uncaught SyntaxError: Identifier 'AxisLayer' has already been declared`, for example.

**Comment by jtpdowns** [comment]
@j6k4m8 I'm unable to reproduce this with the dockerized pytri on the current master branch. Could you try on the docker boi and let me know if you still see this?

**Comment by j6k4m8** [comment]
Still getting this, even in Docker. I think we'll need to do something like `AxisLayer = AxisLayer || ( ... )` to avoid redeclaring things in the same scope.

**Comment by j6k4m8** [comment]
Oh. Hang tight on this. Might be a PEBKAC error.

**Comment by j6k4m8** [comment]
Confirmed.
