### ISSUE TITLE
Modify substrate and pytri for better interaction

### ISSUE THREAD

**Issue by jtpdowns** [iscoe/pytri#19]
In recent changes, we directly altered the props of the visualizer because the target DOM element was not otherwise alterable. We also added a phantom DOM element that we immediately delete to work around the Visualizer constructor. We control both APIs, so we should try to expose something more useful. Also worth thinking about other potential non-disruptive changes to substrate that could make the pytri code more elegant.

**Comment by j6k4m8** [comment]
@jtpdowns have we solved this issue yet?

**Comment by j6k4m8** [comment]
Solved in #83
