### ISSUE TITLE
Be able to resize pytri window

### ISSUE THREAD

**Issue by hpcowley** [iscoe/pytri#39]
Need a way to modify how big our pytri window is (or, alternatively, just to zoom farther out). Becomes a problem in trying to viz huge graphs.

**Comment by j6k4m8** [comment]
We have substrate hooks for this with `Visualizer#resize`. We'll need to just add a function to call that JS.

[Essentially, this.](https://github.com/iscoe/pytri/blob/master/pytri/__init__.py#L102)

**Comment by j6k4m8** [comment]
Solved in #83
