### ISSUE TITLE
Can't set colors for graph/large_graph

### ISSUE THREAD

**Issue by mlw214** [iscoe/pytri#44]
I'm having trouble setting the colors of plotted networkx graphs via `graph` and/or `large_graph`. It seems the `c` argument isn't actually doing anything. See the screenshots below. As you can see, the colors did not change when I passed them via the `c` argument. I also tried stuff like 'red'.

**No color arguments**
<img width="1115" alt="large_graph_default_colors" src="https://user-images.githubusercontent.com/6226856/33395811-afd8c5e8-d514-11e7-9cd1-8b0de08702dc.png">

**Color arguments**
<img width="1108" alt="large_graph_custom_colors" src="https://user-images.githubusercontent.com/6226856/33395810-afd18c2e-d514-11e7-9a16-5823d89f5e4f.png">

**Comment by j6k4m8** [comment]
[This JS](https://github.com/iscoe/pytri/blob/master/pytri/js/GraphLayer.js#L28) is not being invoked by [this Python](https://github.com/iscoe/pytri/blob/master/pytri/__init__.py#L289). Can do a deeper dive in a bit, but this should be a good place to look first

**Comment by j6k4m8** [comment]
As for `large_graph`: I think @hpcowley mentioned that she didn't include colors in her implementation. Help very appreciated on this!
