### ISSUE TITLE
Make position and rotation less brittle

### ISSUE THREAD

**Issue by hpcowley** [iscoe/pytri#54]
If a user only inputs one key in the rotation dictionary (ie: `rotation={'x': Math.pi/2}`), we should support it and not fail silently

**Comment by j6k4m8** [comment]
This is probably most easily done with

```python
rotation = { 'x': 0, 'y': 0, 'z': 0 }
my_rotation = { 'x': 2 }
rotation.update(my_rotation)
```

Now `rotation` is `{ 'x': 2, 'y': 0, 'z': 0 }`
