### ISSUE TITLE
Incompatibility with networkx 2.2

### ISSUE THREAD

**Issue by hpcowley** [iscoe/pytri#91]
We should either: refactor for compatibility with networkx 2.2 or force a networkx 1.9 install. Currently, `requirements.txt` installs the most recent networkx.

@j6k4m8 , I know this is an issue we've been working around for a bit. Thoughts? I can't remember where we netted out last time we talked about this.

**Comment by j6k4m8** [comment]
OH.
BROTHER.

We definitely shouldn't mandate an old nx. Where are we incompatible?

**Comment by hpcowley** [comment]
I was developing on the wrong networkx. We're all good! Sorry for the confusion.
